version: '3.9'

services:
  db:
    image: dbeaver/cloudbeaver:latest
    container_name: dbeaver
    restart: always
    ports:
      - "8978:8978"
    volumes:
      - dbeaver-data:/opt/cloudbeaver/workspace/.RUNTIME
      - dbeaver-logs:/opt/cloudbeaver/logs

volumes:
  dbeaver-data:
  dbeaver-logs:
