version: '3'

services:
  cache:
    image: eqalpha/keydb:alpine
    container_name: keydb
    restart: always
    ports:
      - '6379:6379'
    volumes: 
      - cache:/data

volumes:
  cache:
    driver: local