version: '3.8'

services:
  cache:
    image: eqalpha/keydb:alpine
    container_name: keydb
    restart: always
    ports:
      - '6379:6379'
    environment:
      REDIS_HOST: cache
      REDIS_PORT: 6379
      REDIS_PASSWORD: xxxx
    volumes: 
      - cache:/data

volumes:
  cache:
    driver: local