version: '3'

services:
  db:
    image: cassandra:latest
    container_name: cassandra
    restart: always
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=my-cluster
      - CASSANDRA_CONTACT_POINTS=cassandra
    volumes:
      - cassandra-data:/var/lib/cassandra

volumes:
  cassandra-data: