version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: postgres
    env_file: .env
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
      
  spring:
    build: .
    container_name: spring
    env_file: .env
    ports:
      - '8080:8080'
    depends_on:
      - db
    
# command to run docker compose
# docker compose -f .\docker-compose.yaml up -d