version: '3.9'

services:
  db:
    image: neo4j:latest
    container_name: neo4j
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/test_db
    volumes:
      - neo4j-data:/data

volumes:
  neo4j-data: