version: '3'

services:
  cache:
    image: valkey/valkey:7.2.6-alpine
    container_name: valkey
    restart: always
    ports:
      - '6379:6379'
    volumes: 
      - cache:/data

volumes:
  cache:
    driver: local