version: '3.8'

services:

  db:
    image: postgres:latest
    container_name: postgres
    env_file: .env
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

  fastapi:
    build: .
    env_file: .env
    container_name: fastapi
    ports:
      - "8000"
    volumes:
      - ./app/:/app
    depends_on:
      - db

  web_server:
    image: nginx:latest
    container_name: nginx_sketch
    ports:
      - "80:80"
    depends_on:
      - fastapi
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro