version: '3.8'
services:
  mongo:
    image: mongo:4.2.24-bionic
    container_name: mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: test_db
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD: Fate1234
    volumes:
      - /mongo:/data/db