version: '3.9'

services:
  web:
    image: odoo:17.0
    depends_on:
      - mydb
    ports:
      - "8069:8069"
    environment:
    - HOST=mydb
    - USER=odoo
    - PASSWORD=myodoo
  mydb:
    image: postgres:15
    environment:
      - POSTGRES_DB=odoo_db
      - POSTGRES_PASSWORD=myodoo
      - POSTGRES_USER=odoo
