version: '3'

services:

  db:
    image: postgres:latest
    container_name: postgres
    env_file: .env
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

  fastapi:
    build: .
    env_file: .env
    container_name: fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./{pwd}/:/app
    depends_on:
      - db

# Change {pwd} to your app root folder name