version: '3.9'

services:
  db:
    image: memcached:latest
    container_name: memcached
    restart: always
    ports:
      - "11211:11211"
    command: memcached -m 64 -o modern -v
    volumes:
      - memcached-logs:/var/log/memcached

volumes:
  memcached-logs: