version: '3'

services:
  pocketbase:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pocketbase
    ports:
      - "8080:8080"
    volumes:
      - pocketbase_data:/pb/pb_data
    restart: unless-stopped

volumes:
  pocketbase_data:
    driver: local