version: '3'

services:
  db:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root-password
      MYSQL_DATABASE: dummy_db
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: mariadb-password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
