version: '3.9'

services:
  db:
    image: couchdb:latest
    container_name: couchdb
    restart: always
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=couchdb
      - COUCHDB_PASSWORD=couchdb-password
    volumes:
      - couchdb-data:/opt/couchdb/data

volumes:
  couchdb-data: