version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres
    env_file: .env
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

  app:
    build: .
    env_file: .env
    container_name: cms
    ports:
      - "8000"
    volumes:
      - static-data:/vol/static
    depends_on:
      - db

  proxy:
    build:
    context: ./proxy
    env_file: .env
    volumes:
      - static-data:/vol/static
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
    static-data: