version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - '5050:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Fate1234
      POSTGRES_DB: dummy_db
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    # networks:
    #   - postgres

# networks:
#   postgres:
#     driver: bridge

volumes:
  postgres: