version: '3'

services:

  db:
    image: postgres:latest
    container_name: postgres
    env_file: .env
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

  app:
    build: .
    env_file: .env
    container_name: [name]
    ports:
      - "8000:8000"
    volumes:
      - static-data:/static
    depends_on:
      - db

volumes:
    static-data:
